version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: e-procurement-app
    container_name: e_procurement_app
    volumes:
      - .:/var/www
    networks:
      - e_procurement_network
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - e_procurement_network
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: user_password
    ports:
      - "3312:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - e_procurement_network

volumes:
  mysql_data:

networks:
  e_procurement_network:
